spring.application.name=Spring Boot Application with - OAuth

# Google OAuth2 Configuration


## Stored in Environmental Variables
## Google Client Id,Google Client Secret stored in environment variables
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile

# Optional but recommended
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Logging (optional - helps debugging)
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/oauth_demo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect